### ISSUE TITLE
Understanding decoded output

### ISSUE THREAD

**Issue by brunosegiu** [Mach1Studios/m1-sdk#7]
Hi. I'm testing the examples.

```    m1Encode.generatePointResults();
    m1Decode.beginBuffer();
    std::vector<float> decodedGains = m1Decode.decode(0, 0, 0);
    m1Decode.endBuffer();
    std::vector<float> volumesPerChannel = m1Encode.getResultingCoeffsDecoded(Mach1DecodeAlgoType::Mach1DecodeAlgoSpatial, decodedGains);
```
This snippets results in 4 decoded coefficients. Which as far as I understand should be used to set each channel volume (L-R). 

How do I map these four values to the left and right channels?

Setup:
```
    m1Encode.setInputMode(Mach1EncodeInputModeType::Mach1EncodeInputModeStereo);
    m1Encode.setOutputMode(Mach1EncodeOutputModeType::Mach1EncodeOutputModeM1Spatial);
    m1Encode.setAzimuth(0);
    m1Encode.setDiverge(0.3);
    m1Encode.setElevation(0);
    m1Encode.setIsotropicEncode(true);
    m1Encode.setStereoRotate(0);
    m1Encode.setStereoSpread(0.5);

    m1Decode.setDecodeAlgoType(Mach1DecodeAlgoSpatial);
```

**Comment by himwho** [comment]
Just a little context [getResultingCoeffsDecoded()](https://github.com/Mach1Studios/m1-sdk/blob/master/include/cpp/Mach1Encode.cpp#L113-L118) is a shorthand way to decode (playback with orientation) a single encode object (mono/stereo input you want to pan spatially), usually used for any sort of single preview function or for making custom object audio engines. Depending on what you are trying to develop you may prefer to have all your encode objects sum to a mixer that can sum or render the entire spatial soundfield, if that is not needed than you can also use this function to stack all the already orientation-decoded stereo outputs together as a fully customized spatial audio engine you can build off.

With that context in place, since you set that m1Encode's object input as a "stereo" input via `m1Encode.setInputMode(Mach1EncodeInputModeType::Mach1EncodeInputModeStereo)` then the 4 coeffs returned would represent:

input-stereo1 L
input-stereo1 R
input-stereo2 L
input-stereo2 R

Hope that helps, it seems like we should maybe make the documentation a little clearer?

**Comment by brunosegiu** [comment]
Thanks for your input! Makes complete sense, so if one was to output this results to headphones it should be as simple as summing the L and R channels.
I agree, having a similar explanation in the docs would be great!

**Comment by himwho** [comment]
> Thanks for your input! Makes complete sense, so if one was to output this results to headphones it should be as simple as summing the L and R channels.

yeah with that function you can copy the each of the input streams twice (making the four streams) apply the coeffs returned per orientation update and sum them together into 2 output streams to quickly get a single object style spatializer. Although depending on the usecase you may not want to use this shorthand function if you ever plan on saving or rendering the spatial soundfield or if you want to design "creator tools" of some kind and not only a runtime spatial playback.
